#
# If you don't understand these options, VISIT THE WIKI (it could be very helpful)
# Wiki for more information: https://teik.gitbook.io/epicreports/
#
# Remember that to use it on your network you need to put the plugin on your
# bungeecord, on each server and also connect all of them to the same database
#

Language: en_EN.yml

Reports_Settings:
  Max_reports_per_person: true
  max_reports: 5
  report_offline_players: true
  activate_ers_menu_alias: true
  ers_menu_alias: "reports"

Notify_Settings:
  notify_reports_msg: true
  notify_reports_title: true
  notify_reports_sounds: true
  report_sound: BLOCK_NOTE_BLOCK_PLING;10;2
  notify_processed_reports_msg: true
  notify_processed_reports_title: true
  notify_processed_reports_sounds: true
  report_processed_sound: BLOCK_NOTE_BLOCK_PLING;10;2
  skip_reports: true
  minimum_size_to_skip: 5

Discord_Notifications: true

Network_Settings:
  MySQL-active: false
  MySQL:
    host: "localhost"
    port: 3306
    database: "epicreports"
    user: "root"
    password: "1234"